version: '3'
services:
  postgres:
    container_name: postgres-memorialflow
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MemorialFlow
      PG_DATA_PATH: /var/lib/postgresql/memorialflow
    ports:
      - '5433:5433'
    command: -p 5433
    volumes:
      - ./db/postgres:/var/lib/postgresql/memorialflow
      - ./db/postgres/init:/docker-entrypoint-initdb.d
